# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  RAILS_ENV: production
  FOREMAN_VERSION: 3.1-stable
  RUBY_VERSION: '2.7'
  NODEJS_VERSION: '12'
  DATABASE_URL: nulldb://nohost
  BUNDLER_SKIPPED_GROUPS: "test development openid libvirt journald facter console"
  FOREMAN_FQDN: foreman.example.com
  FOREMAN_DOMAIN: example.com
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Foreman Patch
      uses: actions/checkout@v4
      with:
        path: foreman_patch
    - name: Checkout Foreman
      uses: actions/checkout@v4
      with:
        repository: theforeman/foreman
        ref: ${{ env.FOREMAN_VERSION }}
        path: foreman
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libqpid-proton11-dev libxml2-dev libcurl4-openssl-dev gettext
    - name: Configure Foreman
      working-directory: foreman
      run: |
        cat <<EOF > bundler.d/foreman_patch.rb
        gem 'katello', '~> 4.3.0'
        gem 'foreman-tasks', '~> 5.2.3'
        gem 'foreman_remote_execution', '~> 5.0.8'
        gem 'foreman_patch', path: '$GITHUB_WORKSPACE/foreman_patch'
        EOF

        bundle config set --local without "${BUNDLER_SKIPPED_GROUPS}"
        bundle config set --local clean true
        bundle config set --local path vendor
        bundle config set --local jobs 5
        bundle config set --local retry 3

        bundle install
        bundle binstubs --all

        rm -rf vendor/ruby/*/cache/*.gem
        find vendor/ruby/*/gems -name "*.c" -delete
        find vendor/ruby/*/gems -name "*.o" -delete

        make -C locale all-mo
        mv -v db/schema.rb.nulldb db/schema.rb
        bundle exec bin/rake assets:clean assets:precompile apipie:cache:index

        npm install --no-optional
        ./node_modules/webpack/bin/webpack.js --config config/webpack.config.js
        npm run analyze
    - name: Compile Foreman Patch Assets
      working-directory: foreman
      run: |
        bundle exec bin/rake plugin:assets:precompile[foreman_patch] --trace
    - name: Build Gem
      working-directory: foreman_patch
      run: |
        gem build foreman_patch.gemspec
